site_name: Game
site_url: https://takafumi-nishii.github.io/streamlit-practice/
theme:
  name: material
nav:
  - Home: index.md
  - About: about.md
repo_url: https://github.com/takafumi-nishii/streamlit-practice
extra:
  version:
    provider: mike